### ISSUE TITLE
[Ideia]: Versões aprovadas pelo CoPaJE da proposta de lei

### ISSUE THREAD

**Issue by migmoroni** [CoPaJE/CoPaJE#19]
### Contexto

Hoje possuimos apenas uma proposta, que esta sendo contantemente modificada, de forma a não haver um controle geral, apenas sendo os controles de entrada de assuntos, a cada proposta que é enviada via Pull Request.

Dessa forma, implementar sistema de releases, permitindo que haja uma nova versão a cada vez que o CoPaJE se reunir e votar uma release oficial, se demonstra essencial para que o movimento tenha um documento que defenda e possa ser compartilhado e lido facilmente.

### Descrição

Descrito acima

### Termos

- [X] Eu li e concordo com os termos de contribuicao comunidade no link abaixo ⬇️.

**Comment by tolstenko** [comment]
Acabei de finalizar essa atividade. Agora temos releases versionadas e uma release que mantem apenas a ultima versao. veja em https://github.com/CoPaJE/CoPaJE/releases

**Comment by tolstenko** [comment]
@migmoroni checa se o q eu fiz atende sua demanda

**Comment by migmoroni** [comment]
@tolstenko Há ainda uma pequena incorreção no texto do pdf, onde a cada tópico primeiro de cada página, é copiado o mesmo de forma menor, no cabeçalho superior da página.
Em casos de texto pequeno, insere certo.
Mas em casos de texto comprido, o texto fica cortado.

Há motivo ou necessidade de existir esse texto no cabeçalho superior da página ?

**Comment by tolstenko** [comment]
A ferramenta faz isso. Nao sei como tirar :). Basta lembrar que esse formato eh so temporario e precisamos deixar no formato official do governo. Por mim deixa por hora o PDF ate alguem melhorar. Acho q pode matar essa issue aqui e subir uma de melhorias. 

- Estruturar  formato do PDF no formato esperado pela camara. O que inclui a sua demanda de remover cabecalho de cada pagina.
- Melhorar o texto "none" na pagina inicial.
- Melhorar indices na proposta -> So pode ter 1 elemento H1 com "#"
- Melhorar creditos no pdf.

Para mais detalhes sobre como versionar corretamente, veja esse comentario aqui https://github.com/CoPaJE/CoPaJE/issues/15#issuecomment-1629400827

**Comment by Germano123** [comment]
LGTM.

**Comment by tolstenko** [comment]
Criei outra issue pra rastrear isso aqui #20
